### PR TITLE
Add Emotion API to project-oxford Node Js

### PR DESCRIPTION
**Pull request by mateioprea**
I implemented the Emotion API too. Tested it and it works with local images, url image and faceRectangles.

### CODE REVIEW

**Comment by felixrieseberg** [comment]
Fantastic PR, thank you very much :clap:!

**Comment by felixrieseberg** [comment]
...and pushed to npm :tada:!

**Comment by mateioprea** [comment]
Yaay! Thank you! 🍾🍾🍾🍾

**Comment by mateioprea** [comment]
@felixrieseberg i can help maintaing if you want to.

**Comment by felixrieseberg** [comment]
That's super nice, but we're sort of pseudo-official (I work at Microsoft), so let me figure how legally difficult that would be.

**Comment by mateioprea** [comment]
Ok. Waiting for a reply from you. You can find my email if you access my profile.

**Comment by mateioprea** [comment]
Hey @felixrieseberg. Some news about this? :D

**Pull request merged**
